# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 1000

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[Aiurâ¯](#ff1493)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[QAQ ğŸ‘¾ ](cyan)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[golang]
format = "via [ğŸğŸ’¨$version](bold cyan) "

[git_status]
disabled = true

[time]
disabled = false
style="bold #ff1493"
format = '[\[$time\]]($style) '
time_format = "%H:%M:%S/%a"
utc_time_offset = "+8"
# time_format = "%T"
# utc_time_offset = "+8"
# time_range = "10:00:00-14:00:00"